fix(workflow): improve error handling in bleeding edge deployment script

diff --git a/.github/workflows/bleeding-edge-dist.yml b/.github/workflows/bleeding-edge-dist.yml
--- a/.github/workflows/bleeding-edge-dist.yml
+++ b/.github/workflows/bleeding-edge-dist.yml
@@ -36,15 +36,15 @@ jobs:
         run: |
           sed -i -e 's/dist/src/g' .gitignore
           git rm -rf packages/*/src    
-          jq 'del(.devDependencies."@rneui/base",.peerDependencies."@rneui/base")' packages/themed/package.json > packages/themed/package.json.temp
-          mv packages/themed/package.json.temp packages/themed/package.json
-          git add .
-          git commit -m "Bleeding Edge Version" -a --no-verify
+          jq 'del(.devDependencies."@rneui/base",.peerDependencies."@rneui/base")' packages/themed/package.json > packages/themed/package.json.temp || { echo "Error modifying package.json"; exit 1; }
+          mv packages/themed/package.json.temp packages/themed/package.json || { echo "Error renaming package.json"; exit 1; }
+          git add . 
+          git commit -m "Prepare Bleeding Edge Version" -a --no-verify
 
       - name: Deploy Bleeding Edge version '@rneui/*' packages
         run: |
           for pkg in $(find ./packages -mindepth 1 -maxdepth 1 -type d -printf '%f\n'); do
                echo "Deploying @rneui/$pkg"
-               git subtree split --prefix packages/$pkg -b $pkg || exit 1  # Adding exit 1 for better failure handling
-               git push origin $pkg:refs/heads/$pkg --force
+               git subtree split --prefix packages/$pkg -b $pkg || { echo "Error splitting subtree for $pkg"; exit 1; }
+               git push origin $pkg:refs/heads/$pkg --force || { echo "Error pushing subtree for $pkg"; exit 1; }
           done
